changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: "## Breaking changes"
      labels:
        - breaking-change
    - title: "## New features"
      labels:
        - enhancement
    - title: "## Fixes"
      labels:
        - bug
    - title: "## Documentation and translations"
      labels:
        - documentation
        - translation
    - title: "## Maintenance and dependencies"
      labels:
        - maintenance
        - dependencies
    - title: "## Other changes"
      labels:
        - "*"
