name: HACS validation

on:
  push:
  pull_request:
  schedule:
    - cron: "17 4 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    name: Validate HACS repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: HACS validation
        uses: hacs/action@d556e736723344f83838d08488c983a15381059a # 22.5.0
        with:
          category: plugin
          ignore: "issues topics"
          comment: false
